### ISSUE TITLE
Implement HTML into site framework

### ISSUE THREAD

**Issue by seobrand** [GeniusButter/genius#53]
Implement component peices of HTML into siet framework

![150326_genius_butter_task_history](https://cloud.githubusercontent.com/assets/6989251/7188378/4d725d28-e445-11e4-8f96-bd28c39bea72.jpg)

**Comment by egortimofeev** [comment]
design is there. please explain how it needs to function.

**Comment by Jenelle-SEO** [comment]
Egor - Rusty completed this document  - please review and ask any additional questions

http://screencast.com/t/2pU0pmJSG1z

The task history screen allows the user to see the activity that has taken place in his account with regard to the interaction between his apps.

Upon loading, the user would see most recent interactions (probably 25 or 50 on a screen) sorted in descending order by date of interaction.

The top of the screen contains a number functions as described below.

Filter By:  this first drop down would list all the applications that the user has created connections for – such as Facebook, Twitter, Evernote, etc…  Upon selecting an application and clicking refresh, the list would be filtered based on interactions involving that app.

The statuses drop down would contain the values  “Completed”, “Halted”  and “Failed” indicating the 3 states an interaction can be in.

By selection one of these options and hitting refresh,  the users list would then be filtered as follows:

1.	Completed – this would show all transactions that were successfully completed.

2.	Halted – this would show transactions that did not execute because the user has paused activity on one or both of the applications involved in the connection

3.	Failed – this would filter the list to show transactions that could not be completed due to an error.

The search box allows the user to type in free form text which would then be used to search the contents of each recorded interaction and displayed the filtered results below.

There will be the capability to export the current list of interactions to an excel file, should the user wish to download them for whatever purpose they desire.

NOTE:  Please note that the line in the screen mock indicated with a red box does not actually belong on this screen and will be removed.

**Comment by Jenelle-SEO** [comment]
Bumping up - also Genius is misspelled in the Filter
